---
language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

env:
    - TIKA_VER="1.18"
      TIKA_APP_JAR=/tmp/tika-app-${TIKA_VER}.jar

before_script:
    - >
        curl -o ${TIKA_APP_JAR}
        https://archive.apache.org/dist/tika/tika-app-${TIKA_VER}.jar

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install coveralls

# command to run tests
script:
    - >
        coverage run
        --source=tikapp/
        --omit=tikapp/__main__.py,tikapp/version.py
        tests/test_tika_app.py
    - >
        coverage run
        --source=tikapp/
        --omit=tikapp/__main__.py,tikapp/version.py
        tests/performance.py
    - python -m tikapp -v
    - python -m tikapp -h
    - python -m tikapp -a -f tests/files/test.zip
    - python -m tikapp -a -k < tests/files/test.zip

after_success:
    coveralls

notifications:
    email: false
    slack:
        secure: "gLkkwrBjb0jCuiqMCRM5hXPzYH+LNA5UpMcvjULKtvywVnFVren0UYVyp6h81eQhsvIZecghESTitwRwL7Ttl9/TEmiJ1fuD/pjUbRtUDQourm3zpPAlxppVaj61Hfnln6MyPW+1QIlfXpOJRl+k7RrLKTm0FxXP6TS9t9t+p97ZIVz/iOVGwYWNgeSIdxy6sdzISkMx3i3bn7tr/ILruc18wqbaBs7GzQpgjaFl0S+7PDv4vBmj/9dTYxku6G+nSuzz+Do+BXAMCdcSEn4O4HT+tYyxmkCgRqn7zM8KtAXQwNkuSdjTOZo3Pn917jZibrEj8SaqbfXW1Q2BSN30zTk6p0Y22DF26qbYcy1XX6VDL52oy9GCGth1vNGNkLh/rFQHhZfCXvaSz1jws9vrtbEtHPXaYqfA+p/Xi01N1ewLMaL8yWA9NnCNF9r178bjiKtb7TAWu7B2o2I1j3FqfvtXsQsCQvNGTUc0LFP6i3geS056J8jrtz21IXvUmAJLHY5Qx9j88/lwA2HnhJquY7pFUztjXTgl2JBsBeGgzyoERnhq75iWQATteqbBkW1t5jkivw8g5QNbwln10PQij0SvvV9Cr02W7yX2nXt77/YeHR7ddwxxTNK8xUcjJJGUdB3AAGq1R92G/rEs4WfTniS8wG0CksOqyZ2BF1Q0gdk="
